language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly
jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
addons:
  apt:
    packages:
      - cvs
      - cvsps
      - rcs
before_script:
  - export VCS_TEST_CONFIG='{"paths":{"ci":"\/usr\/bin\/ci","co":"\/usr\/bin\/co","rcs":"\/usr\/bin\/rcs","rcsdiff":"\/usr\/bin\/rcsdiff","rlog":"\/usr\/bin\/rlog","cvs":"\/usr\/bin\/cvs","cvsps":"\/usr\/bin\/cvsps","cvsps_home":"\/tmp","svn":"\/usr\/bin\/svn","diff":"\/usr\/bin\/diff","git":"\/usr\/bin\/git"}}';
  - phpenv config-rm xdebug.ini || echo "XDebug not enabled"
  - pear install channel://pear.horde.org/Horde_Test
  - pear install -a -B package.xml
script:
  - php $(pear config-get php_dir)/Horde/Test/vendor/phpunit/phpunit/phpunit
